-  넘파이 실습

In [3]:
math=[67,43,14,89,50] #수학점수
eng=[78,98,56,87,44] #영어점수

math+eng

[67, 43, 14, 89, 50, 78, 98, 56, 87, 44]

In [4]:
# 리스트로 합구하기
hap=[]
for i in range(len(math)):#0,1,2,3,4
    hap.append(math[i]+eng[i])

hap

[145, 141, 70, 176, 94]

In [5]:
# 넘파이 배열로 합구하기
import numpy as np

mathNum=np.array(math)
engNum=np.array(eng)

print(mathNum)
engNum

[67 43 14 89 50]


array([78, 98, 56, 87, 44])

In [6]:
mathNum+engNum

array([145, 141,  70, 176,  94])

- BMI 구하기

height=[1.67,1.78,1.68]
weight=[78,56,47]

np_height=np.array(height)
np_weight=np.array(weight)

bmi=np_weight/(np_height**2)
print("대상자들의 BMI:")
bmi

- Pandas 예제실습

In [7]:
#Series 생성
import pandas as pd


num=[i for i in range(1,11)]

seriesNum=pd.Series(num)
seriesNum

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [8]:
# Series요약통계

seriesNum.sum()
seriesNum.mean()
seriesNum.std()
seriesNum.median()

seriesNum.describe() #요약통계



count    10.00000
mean      5.50000
std       3.02765
min       1.00000
25%       3.25000
50%       5.50000
75%       7.75000
max      10.00000
dtype: float64

In [9]:
# 딕셔너리 =>시리즈
num2=pd.Series({'a':1,'b':2,'c':3,'d':4})
num2

a    1
b    2
c    3
d    4
dtype: int64

In [10]:
num2[0] #인덱스 번호로 추출
num2['c'] #인덱스 이름으로 추출

/tmp/ipykernel_34968/1350838156.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  num2[0] #인덱스 번호로 추출


3

- 결측치 확인

In [11]:
s=pd.Series([1,2,np.nan,4,5])
s

0    1.0
1    2.0
2    NaN
3    4.0
4    5.0
dtype: float64

In [12]:
#결측치 확인
s.isnull()
s.isnull().sum()

1

In [13]:
#결측치처리_채워넣기
s.fillna(0)#원본적용x
s.fillna(0,inplace=True)#원본적용O
s


0    1.0
1    2.0
2    0.0
3    4.0
4    5.0
dtype: float64

In [14]:
#결측치처리_삭제
a=pd.Series([1,2,np.nan,4,5,7,np.nan])
a


0    1.0
1    2.0
2    NaN
3    4.0
4    5.0
5    7.0
6    NaN
dtype: float64

In [15]:
a.dropna()

0    1.0
1    2.0
3    4.0
4    5.0
5    7.0
dtype: float64

- DataFrame 생성

In [16]:
#dataframe 생성

nums=[[1,2,3],[4,5,6],[7,8,9]]
dfnums=pd.DataFrame(nums)
dfnums

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [17]:
#정보
dfnums.shape #행렬정보
dfnums.shape[0]
dfnums[0].sum()
dfnums+3

0   1   2
0   4   5   6
1   7   8   9
2  10  11  12

In [18]:
#행,열별로 합계구하기
dfnums.sum(axis=1) #가로방향 각 행별 합계
dfnums.sum(axis=0) #세로방향 각 행별 합계


0    12
1    15
2    18
dtype: int64

- 컬럼명 생성

In [19]:
users=[['철수',160,16],['영희',158,18],['민수',170,19],['짱구',133,7]]
dfusers=pd.DataFrame(users)
dfusers

0    1   2
0  철수  160  16
1  영희  158  18
2  민수  170  19
3  짱구  133   7

In [20]:
#컬럼명 생성

dfusers.columns=['name','height','age']
dfusers


name  height  age
0   철수     160   16
1   영희     158   18
2   민수     170   19
3   짱구     133    7

In [21]:
#인덱스명 생성

dfusers.index=['학생1','학생2','학생3','학생4']
dfusers

name  height  age
학생1   철수     160   16
학생2   영희     158   18
학생3   민수     170   19
학생4   짱구     133    7

In [22]:
dfusers['height'].sum()

621

- 인덱스로 행 추출

In [23]:
#인덱스명으로 추출

dfusers.loc['학생3']
dfusers.loc[['학생1','학생3']]
dfusers.loc['학생1','age']
dfusers.loc['학생3',['name','age']]


name    민수
age     19
Name: 학생3, dtype: object

In [24]:
# 인덱스번호로 행 추출

dfusers.iloc[0]
dfusers.iloc[[0,2]]
dfusers.iloc[0,0]
dfusers.iloc[0,[0,1]]

name       철수
height    160
Name: 학생1, dtype: object

- 새로운 열생성

In [25]:
# 새로운 열생성
dfusers['weight']=[80,67,30,17]
dfusers

name  height  age  weight
학생1   철수     160   16      80
학생2   영희     158   18      67
학생3   민수     170   19      30
학생4   짱구     133    7      17

In [26]:
# 새로운 열생성(위치지정)

dfusers.insert(2,'Type',['A','B','O','AB'])
dfusers

name  height Type  age  weight
학생1   철수     160    A   16      80
학생2   영희     158    B   18      67
학생3   민수     170    O   19      30
학생4   짱구     133   AB    7      17

In [27]:
# 부울링 인덱싱

dfusers['height']>=150
dfusers['Type']=='A'
dfusers[dfusers['Type']=='A']


name  height Type  age  weight
학생1   철수     160    A   16      80

In [28]:
(dfusers['height']>=150) & (dfusers['weight'] <=70) #and
(dfusers['height']>=150) | (dfusers['weight'] <=70) #or

학생1    True
학생2    True
학생3    True
학생4    True
dtype: bool

In [29]:
# 정렬
dfusers.sort_values(by='age') #오름차순
dfusers.sort_values(by='age',ascending=False) #내림차순

name  height Type  age  weight
학생3   민수     170    O   19      30
학생2   영희     158    B   18      67
학생1   철수     160    A   16      80
학생4   짱구     133   AB    7      17

In [30]:
# 열삭제
dfusers.drop('age',axis=1,inplace=True)
dfusers

name  height Type  weight
학생1   철수     160    A      80
학생2   영희     158    B      67
학생3   민수     170    O      30
학생4   짱구     133   AB      17

In [31]:
del dfusers['Type']
dfusers

name  height  weight
학생1   철수     160      80
학생2   영희     158      67
학생3   민수     170      30
학생4   짱구     133      17

In [32]:
datas=[['Alice',24,'New York'],['Bob',27,'Los Angeles'],['Charlie',22,'Chicago'],['David',32,'Houston'],['Eve',29,'Phoenix']]
dfdatas=pd.DataFrame(datas)
dfdatas

0   1            2
0    Alice  24     New York
1      Bob  27  Los Angeles
2  Charlie  22      Chicago
3    David  32      Houston
4      Eve  29      Phoenix

- 람다함수

In [33]:
(lambda x: 2*x)(2)

4